### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  usv:   192.168.147.211
  suav:  192.168.147.21
  suavmini: 192.168.147.22
  tuav1: 192.168.147.31
  tuav1: 192.168.147.42
  tuav2: 192.168.147.43
  arm: 192.168.147.168
  local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /mavros/imu/data
  msg_type: sensor_msgs/Imu
  max_freq: 200
  srcIP: self
  srcPort: 1101

- topic_name: /tuav1_takeoff_flag
  msg_type: std_msgs/Int8
  max_freq: 1
  srcIP: self
  srcPort: 1102
  
- topic_name: /target_lidar_position
  msg_type: geometry_msgs/Pose2D
  max_freq: 10
  srcIP: self
  srcPort: 1107

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /target_nav_position
  msg_type: geometry_msgs/Pose2D
  srcIP: suav
  srcPort: 2101

- topic_name: /usv_nav_position
  msg_type: geometry_msgs/Pose2D
  srcIP: suav
  srcPort: 2102

- topic_name: /usv/largebox_pos
  msg_type: geometry_msgs/PoseStamped
  srcIP: arm
  srcPort: 1101