### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  usv:   192.168.147.211
  suav:  192.168.147.21
  suavmini: 192.168.147.22
  tuav1: 192.168.147.42
  tuav2: 192.168.147.43
  tuav3: 192.168.147.51
  arm: 192.168.147.168
  local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /tuav2_des_pos
  msg_type: geometry_msgs/Vector3
  max_freq: 20
  srcIP: self
  srcPort: 4105

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /tuav2_takeoff_flag
  msg_type: std_msgs/Int8
  srcIP: tuav1
  srcPort: 3101

- topic_name: /usv/mavros/imu
  msg_type: sensor_msgs/Imu
  srcIP: usv
  srcPort: 1101

- topic_name: /tuav3_des_pos
  msg_type: geometry_msgs/Vector3
  srcIP: tuav3
  srcPort: 5105

- topic_name: /tuav2_stop_flag
  msg_type: std_msgs/Int8
  srcIP: tuav2
  srcPort: 1104

- topic_name: /usv/largebox_pos
  msg_type: geometry_msgs/PoseStamped
  srcIP: arm
  srcPort: 1101

- topic_name: /usv/usvarm_detect
  msg_type: std_msgs/Int8
  srcIP: arm
  srcPort: 1102
