### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robot1: 127.0.0.1
  robot2: 127.0.0.2
  groundstation: 127.0.0.1

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /car20/imu # send the messages of this ROS topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  max_freq: 50 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3001 # ports of send_topics should be different

- topic_name: /car30/cmd_vel # send the messages of this ROS topic
  msg_type: geometry_msgs/Twist # ROS message type (rosmsg style)
  max_freq: 50 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3002 # ports of send_topics should be different

- topic_name: /car40/imu # send the messages of this ROS topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  max_freq: 50 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3003 # ports of send_topics should be different


####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /car20/imu_recv # the received messages will be published in this topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  srcIP: groundstation # message source IPname
  srcPort: 3001 # message source port

- topic_name: /car30/cmd_vel_recv # the received messages will be published in this topic
  msg_type: geometry_msgs/Twist # ROS message type (rosmsg style)
  srcIP: groundstation # message source IPname
  srcPort: 3002 # message source port
